sftp: switch to phpseclib for uploading

diff --git a/aabs b/aabs
--- a/aabs
+++ b/aabs
@@ -34,6 +34,12 @@ if [ "${AABS_IS_DEV_MACHINE}" != "true" ]; then
 		exit 1
 	fi
 
+	git -C "$AABS_PATH" submodule update --init --recursive >> ${LOGFILE} 2>&1
+	if [ $? -ne 0 ]; then
+		echo -e "\r[ \033[0;31mFAIL\033[0m ] Updating AABS.. Failed! (Please check ${LOGFILE})"
+		exit 1
+	fi
+
 	echo -e "\r[  \033[0;32mOK\033[0m  ] Updating AABS... Finished!"
 fi
 
