hide git-output from wrapper

diff --git a/aabs b/aabs
--- a/aabs
+++ b/aabs
@@ -17,11 +17,24 @@
 #
 
 AABS_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+LOGFILE="$(mktemp "${TMPDIR:-/tmp/}aabs-log.XXXXXX")"
 
 # Update AABS
 if [ "${AABS_IS_DEV_MACHINE}" != "true" ]; then
-	git -C "$AABS_PATH" reset --hard `git -C "${AABS_PATH}" rev-list --max-parents=0 --abbrev-commit HEAD`
-	git -C "$AABS_PATH" pull https://github.com/TeamNexus/aabs master
+	echo -n "[      ] Updating AABS..."
+	git -C "$AABS_PATH" reset --hard `git -C "${AABS_PATH}" rev-list --max-parents=0 --abbrev-commit HEAD` > ${LOGFILE} 2>&1
+	if [ $? -ne 0 ]; then
+		echo -e "\r[ \033[0;31mFAIL\033[0m ] Updating AABS.. Failed! (Please check ${LOGFILE})"
+		exit 1
+	fi
+
+	git -C "$AABS_PATH" pull https://github.com/TeamNexus/aabs master >> ${LOGFILE} 2>&1
+	if [ $? -ne 0 ]; then
+		echo -e "\r[ \033[0;31mFAIL\033[0m ] Updating AABS.. Failed! (Please check ${LOGFILE})"
+		exit 1
+	fi
+
+	echo -e "\r[  \033[0;32mOK\033[0m  ] Updating AABS... Finished!"
 fi
 
 # Start AABS
